
services:
  router:
    build:
      dockerfile: router/Dockerfile
      context: ./
    ports:
      - 8080:8080
  node-1:
    &node-1
    build:
      dockerfile: node/Dockerfile
      context: ./
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - ROUTER_IP=172.18.0.1
    depends_on:
      - router
  node-2:
    <<: *node-1
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - ROUTER_IP=172.18.0.1
    depends_on:
      - node-1
  node-3:
    <<: *node-1
    ports:
      - 8083:8083
    environment:
      - PORT=8083
      - ROUTER_IP=172.18.0.1
    depends_on:
      - node-1
  node-4:
    <<: *node-1
    ports:
      - 8084:8084
    environment:
      - PORT=8084
      - ROUTER_IP=172.18.0.1
    depends_on:
      - node-1
  node-5:
    <<: *node-1
    ports:
      - 8085:8085
    environment:
      - PORT=8085
      - ROUTER_IP=172.18.0.1
    depends_on:
      - node-1