name: Docker Image CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version:'1.18.0'
    - name: Run router test
      run: go test ./router
      

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker log in
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_ACCESS_TOKEN}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Build Router
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/onion-router:router -f router/Dockerfile .
    - name: Publish Router to Docker Hub
      run: docker push ${{secrets.DOCKER_USERNAME}}/onion-router:router
    - name: Build Node
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/onion-router:node -f node/Dockerfile .
    - name: Push Router image to Docker Hub
      run: docker push ${{secrets.DOCKER_USERNAME}}/onion-router:node
    
